---
- name: Remove template
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api.host }}"
    api_user: "{{ proxmox_api.user }}"
    api_token_id: "{{ proxmox_api.token_id }}"
    api_token_secret: "{{ proxmox_api.token_secret }}"
    node: "{{ proxmox_node }}"
    state: absent
    vmid: "{{ proxmox_template.vmid }}"
