---
proxmox_disk_format: "{{ 'raw' if proxmox_template.block_storage else proxmox_template.disk_format }}"
proxmox_image: "{{ proxmox_images[proxmox_template.image] }}"
proxmox_image_location: "{{ proxmox_template.storage }}:\
  {{ proxmox_image_location_prefix }}\
  vm-{{ proxmox_template.vmid }}-disk-0{{ proxmox_image_location_ext }}"
proxmox_image_location_ext: "{{ '' if proxmox_template.block_storage else ('.' ~ proxmox_disk_format) }}"
proxmox_image_location_prefix: "{{ '' if proxmox_template.block_storage else (proxmox_template.vmid ~ '/') }}"
proxmox_image_url:
  image: "{{ proxmox_image.base ~ proxmox_image.name }}"
  digest: "{{ proxmox_image.base ~ proxmox_image.digest }}"
proxmox_images:
  alma_linux_8:
    base: https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/
    name: AlmaLinux-8-GenericCloud-latest.x86_64.qcow2
    digest: CHECKSUM
    method: sha256
  alma_linux_9:
    base: https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/
    name: AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
    digest: CHECKSUM
    method: sha256
  debian_12: &bookworm
    base: https://cloud.debian.org/images/cloud/bookworm/latest/
    name: debian-12-genericcloud-amd64.qcow2
    digest: SHA512SUMS
    method: sha512
  bookworm: *bookworm
  ubuntu_2204: &jammy
    base: https://cloud-images.ubuntu.com/jammy/current/
    name: jammy-server-cloudimg-amd64-disk-kvm.img
    digest: SHA256SUMS
    method: sha256
  ubuntu_2204_minimal: &jammy_minimal
    base: https://cloud-images.ubuntu.com/minimal/releases/jammy/release/
    name: ubuntu-22.04-minimal-cloudimg-amd64.img
    digest: SHA256SUMS
    method: sha256
  jammy: *jammy
  jammy_minimal: *jammy_minimal
proxmox_qm_disk_import: >-
  qm disk import
  {{ proxmox_template.vmid }}
  {{ proxmox_image_dest }}
  {{ proxmox_template.storage }}
  --format {{ proxmox_disk_format }}
