---
- name: Remove k3s nodes and template
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox/vault.yml

  tasks:
    - name: Remove k3s nodes
      ansible.builtin.include_role:
        name: sysengquick.k3s.proxmox
        tasks_from: loop_nodes
      vars:
        proxmox_loop_task: remove_node.yml

    - name: Remove k3s template
      ansible.builtin.include_role:
        name: sysengquick.k3s.proxmox
        tasks_from: remove_template
