---
- name: Add worker to k3s cluster
  ansible.builtin.command:
    cmd: >-
      {{ global_cmd.k3sup }} join
      {{ k3sup_connect_arg }}
      --k3s-version '{{ k3sup_k3s_version }}'
      {{ k3sup_server_connect_arg }}
      --ssh-key '{{ k3sup_ssh_key }}'
      --user '{{ k3sup_user }}'
  changed_when: true
  register: result

- name: Display output
  ansible.builtin.debug:
    msg:
      cmd: "{{ result.cmd }}"
      stdout: "{{ result.stdout_lines }}"
  when: k3sup_debug
