---
- name: Apply kube-vip cloud controller manifest
  ansible.builtin.command:
    cmd: "{{ global_cmd.kubectl }} apply -f {{ k3sup_kube_vip_manifests.cloud_controller }}"
  changed_when: true
  register: result

- name: Display output
  ansible.builtin.debug:
    msg:
      cmd: "{{ result.cmd }}"
      stdout: "{{ result.stdout_lines }}"
  when: k3sup_debug

- name: Apply IP Range to cloud controller
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail &&
      {{ global_cmd.kubectl }} create configmap
      -n kube-system
      kubevip
      -o yaml
      --dry-run=client
      --from-literal range-global={{ k3sup_ip_range.start }}-{{ k3sup_ip_range.end }}
      | {{ global_cmd.kubectl }} apply -f -
    executable: /bin/bash
  changed_when: true
  register: result

- name: Display output
  ansible.builtin.debug:
    msg:
      cmd: "{{ result.cmd }}"
      stdout: "{{ result.stdout_lines }}"
  when: k3sup_debug
