---
proxmox_api:
  host: "{{ proxmox_server }}"
  token_id: ansible
  token_secret: "{{ vault.proxmox_api.token_secret }}"
  user: root@pam

proxmox_image_delete: false
proxmox_image_dest: "/tmp/{{ proxmox_image.name }}"

proxmox_node: pve

proxmox_template:
  block_storage: false
  bridge: vmbr0
  ciuser: "{{ node_ssh_user }}"
  cipassword: "{{ vault.proxmox_template.cipassword }}"
  cores: 4
  disk_format: qcow2
  image: jammy_minimal
  memory: 4096
  name: ansible-k3s-cloud-template
  size: 10G
  ssd: true
  sshkeys: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDaZmy03rApaPZNuN1I8sfmVM/vLv+WD8c2smYyBLJJe sysengquick@wsl2
  storage: local
  vmid: 2500

proxmox_timeouts:
  api: 120
  creation: 15
  startup: 300

# use become plugin for sudo access to qm disk import command
# see notes in create_templae.yml for more information
proxmox_use_become: false
